# Generated by Django 3.2.5 on 2021-07-23 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('love', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowingUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, verbose_name='名称')),
                ('take_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
                ('desc', models.CharField(blank=True, default='', max_length=1024, verbose_name='描述')),
                ('bak_data', models.CharField(blank=True, default='', max_length=1024, verbose_name='备用字段')),
                ('bak_data1', models.CharField(blank=True, default='', max_length=1024, verbose_name='备用字段1')),
                ('pic', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
    ]
